import type {
  AppNotification,
  CommunityRequest,
  Dispute,
  PlatformFeeConfig,
  Resource,
  User,
} from "./types";

export const users: User[] = [
  {
    id: "u1",
    name: "Aarav Mehta",
    initials: "AM",
    department: "Film & Media Club",
    year: "3rd year",
    verified: true,
    trust: 96,
    rating: 4.9,
    exchanges: 41,
    onTime: 98,
    lateReturns: 1,
    disputes: 0,
    responseMinutes: 12,
    memberSince: "Aug 2023",
    badges: [
      "Verified Student",
      "Reliable Lender",
      "Fast Responder",
      "10+ Exchanges",
    ],
  },
  {
    id: "u2",
    name: "Meera Nair",
    initials: "MN",
    department: "Electronics Engineering",
    year: "4th year",
    verified: true,
    trust: 92,
    rating: 4.8,
    exchanges: 31,
    onTime: 97,
    lateReturns: 1,
    disputes: 0,
    responseMinutes: 9,
    memberSince: "Jul 2022",
    badges: ["Verified Student", "Reliable Lender", "Sustainable Contributor"],
  },
  {
    id: "u3",
    name: "Kabir Shah",
    initials: "KS",
    department: "Computer Science",
    year: "2nd year",
    verified: true,
    trust: 88,
    rating: 4.7,
    exchanges: 18,
    onTime: 94,
    lateReturns: 1,
    disputes: 0,
    responseMinutes: 18,
    memberSince: "Jan 2024",
    badges: ["Verified Student", "10+ Exchanges"],
  },
  {
    id: "u4",
    name: "Riya Banerjee",
    initials: "RB",
    department: "Architecture",
    year: "3rd year",
    verified: true,
    trust: 90,
    rating: 4.8,
    exchanges: 24,
    onTime: 96,
    lateReturns: 1,
    disputes: 0,
    responseMinutes: 15,
    memberSince: "Sep 2023",
    badges: ["Verified Student", "Reliable Lender"],
  },
  {
    id: "u5",
    name: "Dev Malhotra",
    initials: "DM",
    department: "Mechanical Engineering",
    year: "4th year",
    verified: true,
    trust: 85,
    rating: 4.6,
    exchanges: 15,
    onTime: 93,
    lateReturns: 1,
    disputes: 0,
    responseMinutes: 22,
    memberSince: "Aug 2022",
    badges: ["Verified Student", "Sustainable Contributor"],
  },
  {
    id: "me",
    name: "Ananya Rao",
    initials: "AR",
    department: "Information Technology",
    year: "3rd year",
    verified: true,
    trust: 91,
    rating: 4.8,
    exchanges: 27,
    onTime: 96,
    lateReturns: 1,
    disputes: 0,
    responseMinutes: 11,
    memberSince: "Jul 2023",
    badges: ["Verified Student", "Fast Responder", "Sustainable Contributor"],
  },
];

export const img = {
  camera:
    "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=82",
  cameraCanon:
    "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=1200&q=82",
  cameraSony:
    "https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=1200&q=82",
  cameraTripod:
    "https://images.unsplash.com/photo-1452780212940-6f5c0d14d848?auto=format&fit=crop&w=1200&q=82",
  laptop:
    "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=82",
  audio:
    "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=82",
  book: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=82",
  electronics:
    "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=82",
  guitar:
    "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=1200&q=82",
  projector:
    "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=1200&q=82",
  tools:
    "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=1200&q=82",
};
const r = (
  id: string,
  title: string,
  category: Resource["category"],
  ownerId: string,
  location: Resource["location"],
  distance: number,
  condition: Resource["condition"],
  availableNow: boolean,
  charge: number,
  deposit: number,
  image: string,
  description: string,
  accessories: string[],
  tags: string[],
  successfulBorrows: number,
  donation = false,
): Resource => ({
  id,
  title,
  category,
  ownerId,
  location,
  distance,
  condition,
  availableNow,
  charge,
  deposit,
  image,
  description,
  accessories,
  tags,
  successfulBorrows,
  donation,
  unavailableDates: availableNow ? [] : ["2026-08-27"],
  conditions: donation
    ? ["Free to keep"]
    : ["Return in the same condition", "Campus use only"],
  pickupOptions: [`${location} meetup`],
});
export const resources: Resource[] = [
  r(
    "r1",
    "Sony α6400 Mirrorless Camera",
    "Cameras",
    "u1",
    "Main Building",
    300,
    "Excellent",
    true,
    180,
    1500,
    img.cameraSony,
    "A sharp lightweight 4K camera ideal for club reels, interviews and event coverage.",
    ["16–50mm lens", "2 batteries", "64GB SD card", "Shoulder bag"],
    ["4K", "reels", "events"],
    27,
  ),
  r(
    "r2",
    "Canon EOS 200D DSLR",
    "Cameras",
    "u4",
    "Library",
    520,
    "Good",
    true,
    120,
    1200,
    img.cameraCanon,
    "Beginner-friendly DSLR with reliable autofocus and excellent still image quality.",
    ["18–55mm lens", "Battery", "Charger"],
    ["photography", "portraits"],
    19,
  ),
  r(
    "r3",
    "Manfrotto Compact Tripod",
    "Cameras",
    "u1",
    "Main Building",
    280,
    "Excellent",
    true,
    40,
    300,
    img.cameraTripod,
    "Stable aluminium tripod for cameras and phones, extending to 155 cm.",
    ["Phone clamp", "Carry sleeve"],
    ["tripod", "reel", "stable"],
    34,
  ),
  r(
    "r4",
    "RØDE Wireless GO II Mic",
    "Audio",
    "u2",
    "Engineering Block",
    340,
    "Like new",
    true,
    90,
    800,
    img.audio,
    "Dual-channel wireless microphone kit for interviews, reels and presentations.",
    ["2 transmitters", "Receiver", "USB-C cables", "Windshields"],
    ["microphone", "interview", "reel"],
    22,
  ),
  r(
    "r5",
    "Portable LED Lighting Kit",
    "Cameras",
    "u4",
    "Innovation Lab",
    610,
    "Excellent",
    true,
    110,
    700,
    img.cameraCanon,
    "Two adjustable LED panels with stands and colour temperature control.",
    ["2 stands", "Diffusers", "Power adapters"],
    ["lighting", "video", "studio"],
    16,
  ),
  r(
    "r6",
    "Casio fx-991EX Calculator",
    "Study",
    "u3",
    "Library",
    140,
    "Good",
    true,
    15,
    100,
    img.electronics,
    "Scientific calculator approved for most university examinations.",
    ["Hard cover"],
    ["calculator", "exam", "engineering"],
    43,
  ),
  r(
    "r7",
    "MacBook Air M2 — 16GB",
    "Computing",
    "u3",
    "Hostel Gate",
    780,
    "Excellent",
    false,
    240,
    3000,
    img.laptop,
    "Fast laptop for editing, coding and presentations. Software suite pre-installed.",
    ["67W charger", "Sleeve", "USB-C hub"],
    ["laptop", "editing", "coding"],
    11,
  ),
  r(
    "r8",
    "Lenovo ThinkPad E14",
    "Computing",
    "u5",
    "Engineering Block",
    410,
    "Good",
    true,
    160,
    2200,
    img.laptop,
    "Reliable Windows laptop with MATLAB, AutoCAD and VS Code configured.",
    ["Charger", "Wireless mouse"],
    ["windows", "CAD", "MATLAB"],
    14,
  ),
  r(
    "r9",
    "Arduino Uno Prototyping Kit",
    "Electronics",
    "u2",
    "Innovation Lab",
    460,
    "Excellent",
    true,
    60,
    500,
    img.electronics,
    "Complete starter kit for IoT and electronics practicals.",
    ["Breadboard", "Jumper wires", "Sensors", "USB cable", "Resistors"],
    ["arduino", "IoT", "prototype"],
    38,
  ),
  r(
    "r10",
    "Digital Multimeter",
    "Electronics",
    "u5",
    "Engineering Block",
    360,
    "Good",
    true,
    30,
    250,
    img.tools,
    "Auto-ranging multimeter for circuit testing and lab projects.",
    ["Probe set", "Protective case"],
    ["multimeter", "lab", "electronics"],
    20,
  ),
  r(
    "r11",
    "Data Structures in C++",
    "Books",
    "u3",
    "Library",
    120,
    "Good",
    true,
    0,
    200,
    img.book,
    "Clean annotated copy with revision flags and solved examples.",
    ["Revision notes"],
    ["DSA", "C++", "textbook"],
    12,
  ),
  r(
    "r12",
    "Engineering Mathematics III",
    "Books",
    "u2",
    "Canteen",
    250,
    "Fair",
    true,
    0,
    0,
    img.book,
    "Previous-edition textbook offered free to a student who needs it.",
    ["Formula sheet"],
    ["mathematics", "donation", "free"],
    0,
    true,
  ),
  r(
    "r13",
    "Yamaha F310 Acoustic Guitar",
    "Instruments",
    "u1",
    "Hostel Gate",
    690,
    "Good",
    true,
    80,
    800,
    img.guitar,
    "Warm-sounding acoustic guitar suitable for rehearsals and small performances.",
    ["Padded bag", "Picks", "Clip tuner"],
    ["guitar", "music", "rehearsal"],
    18,
  ),
  r(
    "r14",
    "Epson Portable Projector",
    "Computing",
    "u4",
    "Main Building",
    330,
    "Excellent",
    false,
    140,
    1500,
    img.projector,
    "Bright portable projector for society screenings, reviews and presentations.",
    ["HDMI cable", "Remote", "Carry case"],
    ["projector", "presentation", "event"],
    21,
  ),
  r(
    "r15",
    "Engineering Drawing Kit",
    "Tools",
    "u4",
    "Main Building",
    290,
    "Good",
    true,
    25,
    150,
    img.tools,
    "Complete drafter, compass and scale set for engineering drawing classes.",
    ["Mini drafter", "Compass", "Set squares", "Scale"],
    ["drawing", "drafter", "engineering"],
    29,
  ),
  r(
    "r16",
    "Bosch Cordless Drill Kit",
    "Tools",
    "u5",
    "Innovation Lab",
    540,
    "Excellent",
    true,
    70,
    650,
    img.tools,
    "Compact drill-driver for prototype builds and supervised workshop use.",
    ["2 batteries", "Bit set", "Safety glasses"],
    ["drill", "prototype", "workshop"],
    13,
  ),
];
export const initialNotifications: AppNotification[] = [
  {
    id: "n1",
    title: "Request approved",
    body: "Aarav approved your tripod request. Choose a pickup slot.",
    time: "8 min ago",
    read: false,
    tone: "green",
  },
  {
    id: "n2",
    title: "Return due tomorrow",
    body: "The Arduino kit is due by 5:00 PM tomorrow.",
    time: "1 hr ago",
    read: false,
    tone: "amber",
  },
  {
    id: "n3",
    title: "New rating received",
    body: "Meera rated your last exchange 5 stars.",
    time: "Yesterday",
    read: true,
    tone: "blue",
  },
];
export const currentUser = users.find((u) => u.id === "me")!;
export const ownerFor = (resource: Resource) =>
  users.find((u) => u.id === resource.ownerId)!;

export const initialFeeConfig: PlatformFeeConfig = {
  percentRate: 5,
  minFee: 10,
  enabled: true,
};

export const initialCommunityRequests: CommunityRequest[] = [
  {
    id: "req-101",
    title: "DJI Osmo Pocket Gimbal",
    category: "Cameras",
    details: "Needed for short documentary interview shoot at Innovation Lab.",
    neededBy: "2026-08-30",
    requesterId: "u3",
    status: "Open",
    createdAt: "2026-08-26T14:30:00.000Z",
  },
  {
    id: "req-102",
    title: "TI-84 Plus CE Graphic Calculator",
    category: "Study",
    details: "Needed for Advanced Statistics mid-semester exam tomorrow.",
    neededBy: "2026-08-28",
    requesterId: "u4",
    status: "Open",
    createdAt: "2026-08-27T09:15:00.000Z",
  },
];

export const initialDisputes: Dispute[] = [
  {
    id: "dsp-401",
    exchangeId: "CC-4821",
    reporterId: "u2",
    reason: "Missing Jumper Wires & Minor Scratches",
    details: "10 jumper wires were missing upon return inspection.",
    evidenceImage:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=82",
    claimedDepositDeduction: 150,
    submittedAt: "2026-08-26T18:20:00.000Z",
    status: "Under Review",
  },
];
